import type { Metadata } from "next";
import { NavbarDemo } from "./_components/common/Navbar";
import { getAiSettings, getFooterDetails } from "../lib/data";
import FooterSection from "./_components/common/footer2";
import { Toaster } from "@/components/ui/sonner";
import Chatbot from "./_components/chatbot/chatbot";

export const metadata: Metadata = {
  title: "1Technologies",
  description: "Generated by create next app",
};

export default async function AppfrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footer = await getFooterDetails();
  const settings = await getAiSettings();

  return (
    <div className=" ">
      <Chatbot settings={settings} />

      <NavbarDemo>
        {children}
        <Toaster position="top-right" richColors />
      </NavbarDemo>
      {/* <Footer data={footer} /> */}
      {footer && <FooterSection data={footer} />}
    </div>
  );
}
