import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "1Technologies",
  description: "Generated by create next app",
};

export default function AppfrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}

const Navbar = () => {
  return (
    <div className=" flex gap-3">
      <Link href="/">Home</Link>
      <Link href="/dashboard">Dashboard</Link>
      <Link href="/profile">Profile</Link>
      <Link href="/hi">Signup</Link>
    </div>
  );
};
