import type { Metadata } from "next";
import { NavbarDemo } from "./_components/common/Navbar";
import Footer from "./_components/common/footer";
import { getFooterDetails } from "../lib/data";
import FooterSection from "./_components/common/footer2";

export const metadata: Metadata = {
  title: "1Technologies",
  description: "Generated by create next app",
};

export default async function AppfrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footer = await getFooterDetails();

  return (
    <div className=" ">
      <NavbarDemo>{children}</NavbarDemo>
      {/* <Footer data={footer} /> */}
      <FooterSection />
    </div>
  );
}
