import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import AppNavbar from "./_components/app-navbar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "1Technologies | Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <SidebarProvider>
          <AppSidebar />
          <main className=" w-full px-2 md:px-8 ">
            <div className=" sticky top-2">
              <AppNavbar />
            </div>
            {children}
            <Toaster position="top-right" richColors />
          </main>
        </SidebarProvider>
      </ThemeProvider>
    </>
  );
}
